### PR TITLE
[WIP] Removed Vapor Dep, replaced w/Embassy. Port to Linux. Update to Swift 4

### PR DESCRIPTION
**Pull request by terhechte**
This is a WIP test commit to see how the project performs when replacing
Vapor with Embassy. Embassy is much more lightweight, resulting in
shorter compile times.

### CODE REVIEW

**Comment by felix91gr** [comment]
I'm now going to post updates to this WIP here. The [Port to Linux thread](https://github.com/terhechte/SourceKittenDaemon/issues/62) will stay as an archive, but I'm closing it because it's very long and most of it consists of the notes I made as I researched that issue.

**Comment by felix91gr** [comment]
### Already achieved
This PR already makes the following possible:

* Builds on Linux using a **Swift 3.1.1 toolchain**. If the [precompiled one](https://swift.org/download/#releases) doesn't work, you might need [Nomura's 3.1.1 cherrypicked branch](https://github.com/norio-nomura/swift/tree/sourcekit-linux-3.1.1-branch).
* Updated to latest `Xcode.swift` release (now called `XcodeEdit`) for better support in the future.
* All dependencies, except Embassy, pass their tests on **Swift 3.1**

### Still left to achieve before merging
These are the goals we want to reach before merging this PR: 

* Help to update Embassy so that it passes its tests on **Swift 3.1**.
* Make SKD pass all of **its tests in Linux**. _Requires Embassy to pass its tests_

**Comment by felix91gr** [comment]
## Current dependency list
And loose ends in them, if any. I'm updating this as the PR progresses.
1. [Carthage's `Commandant`](https://github.com/Carthage/Commandant). Latest version. Works 100%
2. [JP Simard's `SourceKitten`](https://github.com/jpsim/SourceKitten). Latest version. Works 100%
3. [Envoy's `Embassy`](https://github.com/envoy/Embassy). Latest version. Builds. **Tests are not passing**.
_Managed to compile its tests making a small change, but there's still a test that never ends before its timeout. Under Swift 3.0, all the test pass, so the changes necessary must be very small._
4. [Tom Lokhorst's `XcodeEdit`](https://github.com/felix91gr/XcodeEdit). Using a fork that I made for now, while Tom L. fixes the issues that we had. Builds. Doesn't have tests.
5. **_Linux-only_** [My `FileSystemWatcher` fork](https://github.com/felix91gr/FileSystemWatcher). The fork is custom-tailored for our use cases. Builds. Doesn't have tests (yet).
_Wraps a linux C library, inotify, which lets us have `FileStreamEvent` functionality under Linux._

**Comment by felix91gr** [comment]
## Current Status
I want to continue with this PR, but first I need Embassy to work. I’ve asked Fang Pen-Lin again about Embassy and what she plans to do about updating it. It’s possible that it’s not a priority anymore, I haven’t recieved a response from her yet so I don’t actually know. 
I’ve offered my help to her, to see if I can accelerate the migration.

### After it’s settled
Either we will continue with Embassy (hopefully) or we’ll have to drop it if it stops being supported. We can always go back to Vapor anyway, so that’s not a problem I guess.

**Comment by felix91gr** [comment]
# Now that Swift 4 has been released...

Fang-Pen Lin [has just stated](https://github.com/envoy/Embassy/issues/36) that she'll update Embassy to work with Swift 4. As soon as it's working, I'll proceed to test it and go on with the PR, if all goes well :)

**Comment by felix91gr** [comment]
# Update on Embassy

[She updated it, and fixed the issues!](https://github.com/envoy/Embassy/issues/35#issuecomment-331022019) :tada: 

More work on this PR _coming soon :tm:_ 

As soon as I get a break from uni, that is! Maybe in a couple of weeks :)

**Comment by felix91gr** [comment]
Okay, I've been running the tests, and the tests on the dependencies. This is the current status:

**Our tests fail**. Why? First we have to check the dependencies.

* Does SourceKitten work? Yes. Passes all of its tests.
* Does Embassy work? Ye- almost. As I've [pointed out to Fang-Pen Lin](https://github.com/envoy/Embassy/issues/42), the fix she did for the Linux build isn't in any release. Therefore, we cannot use it (afaik) with SPM. I've asked her to push a new release. It should take her 10 minutes, so let's hope it happens soon.

So... a WIP, as always. But we seem to be approaching correctness AND Swift 4.0 in a good way.

**Also,** thanks, @nathankot for merging `master` and making the branch compile! I couldn't have done it better than you did. Thanks :)

**Comment by felix91gr** [comment]
Hmm. Travis passes the tests, but I'm getting a crash (_the suite crashes_) while testing on Linux. 

I'll dig deeper into this tomorrow, if I have the time. If not, I hope I can continue during this week.

WE ARE APPROACHING CORRECTNESS! :muscle:

**Comment by nathankot** [comment]
> WE ARE APPROACHING CORRECTNESS!

👍 So I managed to get the tests passing (I'm on OSX though), but completion isn't working for me at all on Xcode 9 - something I'll look into next weekend

**Comment by felix91gr** [comment]
> but completion isn't working for me at all on Xcode 9 - something I'll look into next weekend

Awesome :) I hope you catch it

Btw, I didn't explain it before, but the test suite is actually crashing -- not failing the tests per se.

Here is the culprit:

In `CompleterTests.swift > setUp()`, we call `try! Project(type: type, configuration: "Debug")`. Through a series of calls, it fails in the following part of the `XCodeEdit`'s `XCProjectFile.swift` file:

_(the debug prints are mine, I cannot include them in a commit tho because it's not our repo)_

```swift

  public convenience init(propertyListData data: Data) throws {


    print("This init is where I crash on Linux...")

    print("Creating and printing MutabilityOptions...")
    let options = PropertyListSerialization.MutabilityOptions()
    
    print("RESULT: ")

    print(options)

    print("Creating and printing PropertyListFormat...")
    var format: PropertyListSerialization.PropertyListFormat = PropertyListSerialization.PropertyListFormat.binary

    print("RESULT: ")
    print(format)

    print("Creating PropertyListSerialization object...")
    let obj = try PropertyListSerialization.propertyList(from: data, options: options, format: &format)

    // print("RESULT: ")
    // print(obj)

    print("Creating and printing Project Fields...")
    guard let dict = obj as? Fields else {
      throw ProjectFileError.invalidData
    }

    print(dict)
    
    print("Everything is set up. Calling self.init...")

    self.init(dict: dict, format: format)
  }
```

The `PropertyList` object seems to be ill-formatted, somehow. The Fields type isn't accepting it. I tried printing it though, and the `PropertyList` isn't nil. So, there's something weird going on :thinking:

**Comment by nathankot** [comment]
@felix91gr I'm not able to reproduce the crash that you described above, I think it might be something to do with linux? I did omit to commit+push one of the test fixes though, so just pushed that now (de8114a). 

On my machine (OSX, Xcode 9.0.1) this branch has *passing tests* and autocompletion works with `company-sourcekit`. I think `9.0.0 -> 9.0.1` might have resolved my previous issue with the completion always returning empty, but to be honest I haven't investigated.

**Comment by felix91gr** [comment]
Nathan, I’m back! And I made a Slack channel ^^

So, getting back to this PR...

How’s it doing on your side? If it works in Mac OS, maybe we should merge it since it’s lighter than the current release. We would be pushing the Linux port’s pending work to the next PR, which I’m inclined to prefer. What do you think?

**Comment by felix91gr** [comment]
Okay it indeed seems to be working on Mac OS.

@terhechte @nathankot I think we should try merging and releasing this as an update for Mac OS:
* It updates the library to `Swift 4.0`
* It uses `Embassy` instead of `Vapor`.

I can finish the port to Linux afterwards. I think the updates for the Mac OS users are too good to have them waiting anymore. What do you guys think?

**Comment by felix91gr** [comment]
I think I found a bug in Foundation.

I made a new Swift 4.0 setup on Linux, and I can't compile this branch. This is what I get in console:

```console
Compile Swift Module 'SourceKittenDaemon' (8 sources)
/home/felix/Documents/Programming/SKD/SourceKittenDaemon/Sources/SourceKittenDaemon

/home/felix/Documents/Programming/SKD/SourceKittenDaemon/Sources/SourceKittenDaemon/Completer/Completer.swift:98:28: error: ambiguous use of 'addObserver'
        NotificationCenter.default.addObserver(
                           ^
Foundation.NotificationCenter:9:15: note: found this candidate
    open func addObserver(forName name: Foundation.NSNotification.Name?, object obj: Any?, queue: Foundation.OperationQueue?, usingBlock block: @escaping (Foundation.Notification) -> Swift.Void) -> NSObjectProtocol
              ^
Foundation.NotificationCenter:10:15: note: found this candidate
    open func addObserver(forName name: Foundation.NSNotification.Name?, object obj: Any?, queue: Foundation.OperationQueue?, using block: @escaping (Foundation.Notification) -> Swift.Void) -> NSObjectProtocol
              ^
error: terminated(1): /home/felix/Documents/Programming/Binaries/swift/swift-4.0.3-RELEASE/usr/bin/swift-build-tool -f /home/felix/Documents/Programming/SKD/SourceKittenDaemon/.build/debug.yaml main

```

I dunno where should I put the bug report. I'm gonna try asking on Twitter :thinking:

**Comment by felix91gr** [comment]
Yup, it's definitely a bug. [Here](https://github.com/apple/swift-corelibs-foundation/blob/swift-4.0-branch/Foundation/NSNotification.swift#L191) are the two conflicting methods. One of them should be obsolete in swift 4.0, but for some reason, the compiler doesn't know that.

**Comment by rudedogg** [comment]
This works correctly for me correctly with Xcode 9.2 and company-sourcekit

**Comment by felix91gr** [comment]
I'm gonna merge this so that our Mac users can go ahead and use SKD on the latest Swift release. We'll push the Linux port for later.

> This works correctly for me with macOS 10.13/Xcode 9.2 and company-sourcekit

Thanks for the feedback! Can I ask you to test it after I merge and make a beta release? I don't have a Mac, and so I rely on the testing of Nathan and our Mac users :)

**Comment by rudedogg** [comment]
@felix91gr Sure!

I checked out `master`, ran`git pull` and made sure I was at tag 0.1.7. Ran `make install`, it went fine and I have completions in company-sourcekit still.

**Comment by felix91gr** [comment]
That’s awesome! Thank you 😊

**Pull request merged**
